# Analysis options for mot_flutter
# Inherits from flutter_lints and adds strict rules

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error

linter:
  rules:
    # Style rules
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_final_parameters
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
